apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-a
spec:
  destination:
    namespace: defaulte
    server: https://kubernetes.default.svc
  project: default
  source:
    path: _api-gw
    repoURL: https://github.com/Nexonix-Co-Ltd/deploy-management-infra-canal-one.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /status/loadBalancer
